"""Mod identity: title chain, save identity, display names, duplicate keys (src/core/identity.py).

Contract: verbatim ports of dd2.py ``normalize_mod_identity`` (546-554), ``save_name``
(3960-3964), ``text_has_latin`` (592), ``looks_like_numeric_id`` (596), ``is_bad_display_title``
(600-620), the localization ranking (3561-3588), the internal code title (3590-3617), the
``read_mod_metadata`` title/save chain (3477-3540) over a ``ModSnapshot``, the display helpers
(3924-4037) and ``duplicate_detection_keys`` / ``category_memory_keys`` (4092-4116, 3142-3204).

Three layers of proof: contract examples (no oracle), committed goldens under
tests/golden/identity (generated by tools/regen_goldens.py from the oracle, so parity outlives the
legacy deletion) and live ``@pytest.mark.legacy`` differential tests on temp mod folders.
"""

import dataclasses
import json
import random
from datetime import UTC, datetime, timedelta, timezone, tzinfo
from pathlib import Path
from typing import Any

import pytest

from src.core.identity import (
    category_memory_keys,
    derive_mod_info,
    display_name,
    display_name_with_suffix,
    display_suffix,
    duplicate_keys,
    internal_code_title,
    is_bad_display_title,
    localization_title,
    looks_like_numeric_id,
    normalize_mod_identity,
    resolve_save_identity,
    sort_key,
    split_numeric_prefix,
    strip_numeric_prefix,
    text_has_latin,
)
from src.core.ids import ModId, SaveIdentity, SaveSource
from src.core.model import ModInfo, ModSnapshot
from src.core.project_xml import ProjectInfo, parse_project
from tests.support import factories
from tests.support import mod_facts as mf
from tools.legacy_oracle import LegacyOracle

GOLDEN_DIR = Path(__file__).absolute().parents[1] / "golden" / "identity"
HELPERS_FILE = GOLDEN_DIR / "helpers.json"
CASES_FILE = GOLDEN_DIR / "cases.json"

_local = datetime.now(UTC).astimezone().tzinfo
assert _local is not None
LOCAL_TZ: tzinfo = _local


def _load_golden(path: Path) -> dict[str, Any]:
    if not path.is_file():
        pytest.fail(
            f"{path} is missing: the identity goldens are the parity proof that outlives the"
            " legacy oracle; restore them from git or run tools/regen_goldens.py",
            pytrace=False,
        )
    return json.loads(path.read_text("utf-8"))


HELPERS = _load_golden(HELPERS_FILE)
CASES = _load_golden(CASES_FILE)


# ----------------------------------------------------------------- pure helpers (contract)


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        ("", ""),
        ("  ", ""),
        ("The Chorus", "the chorus"),
        ('Rogue & Knight\'s "Fate" (v2)', "rogue and knight s fate v2"),
        ("Rogue &amp; Knight", "rogue and knight"),
        ("0001_my_mod", "0001 my mod"),
        ("a\\b/c-d:e;f,g.h(i)j[k]l{m}n'o\"p!q+r", "a b c d e f g h i j k l m n o p q r"),
        ("Café  \t\n X", "café x"),
        ("桜のスキン", "桜のスキン"),
        ("&#39;quoted&#39;", "quoted"),
        ("STRASSE ß", "strasse ß"),
    ],
)
def test_normalize_mod_identity_contract(raw: str, expected: str) -> None:
    assert normalize_mod_identity(raw) == expected


def test_normalize_mod_identity_is_idempotent() -> None:
    for text in mf.identity_corpus(1, 300):
        once = normalize_mod_identity(text)
        assert normalize_mod_identity(once) == once


@pytest.mark.parametrize(
    ("folder", "expected"),
    [
        ("0001_my_mod", "my_mod"),
        ("12_34_mod", "mod"),
        ("1234567890", "1234567890"),  # every part numeric -> folder unchanged
        ("_leading", "_leading"),
        ("mod_0001", "mod_0001"),
        ("abc", "abc"),
        ("", ""),
    ],
)
def test_strip_numeric_prefix_contract(folder: str, expected: str) -> None:
    assert strip_numeric_prefix(folder) == expected


@pytest.mark.parametrize(
    ("name", "expected"),
    [
        ("0001_my_mod", ("0001", "my_mod")),
        ("12_bar", ("12", "bar")),
        ("0001_", ("0001", "")),
        ("1234567_mymod", None),  # the underscore sits beyond the 5-character window
        ("a_1", None),
        ("2024", None),
        ("_x", None),
        ("", None),
    ],
)
def test_split_numeric_prefix(name: str, expected: tuple[str, str] | None) -> None:
    """dd2.py:4017-4020 (display name) and 7290-7293 (apply order) share this one test."""
    assert split_numeric_prefix(name) == expected


@pytest.mark.parametrize(
    ("text", "expected"),
    [("", False), ("123", False), ("桜", False), ("a", True), ("é", False), ("x1", True)],
)
def test_text_has_latin_contract(text: str, expected: bool) -> None:
    assert text_has_latin(text) is expected


@pytest.mark.parametrize(
    ("text", "expected"),
    [("", False), ("123", True), ("12 3", False), ("-1", False), ("١٢", True), ("0", True)],
)
def test_looks_like_numeric_id_contract(text: str, expected: bool) -> None:
    assert looks_like_numeric_id(text) is expected


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("", True),
        ("   ", True),
        ("My Mod", False),
        ("Tooltip", True),
        ("TOOLTIPS", True),
        ("tray_icon", True),
        ("Tooltip Tweaks", False),
        ("50% more", True),
        ("{colour_start|red}X{colour_end}", True),
        ("{color_x}", True),
        ("{colour", True),
        ("<b>Bold</b>", True),
        ("a > b", True),
        ("&lt;i&gt;", True),  # unescaped first, then the <> check
        ("&amp;", False),
        ("Lasts 3 combats", True),
        ("1 combat", True),
        ("combats 3", False),
        ("桜のスキン", False),  # non-Latin is not "bad" (the Latin gate is separate)
        ("1234567890", False),
    ],
)
def test_is_bad_display_title_contract(text: str, expected: bool) -> None:
    assert is_bad_display_title(text) is expected


# ----------------------------------------------------------------- localization / code titles


def test_localization_title_ranking() -> None:
    assert localization_title(mf.LOC_RANKING) == "Abomination Rework"
    without_hero = [e for e in mf.LOC_RANKING if not e[0].startswith("hero_class_name_")]
    assert localization_title(without_hero) == "Al"
    only_titles = [("str_mod_name", "Mod Name"), ("str_ui_title_banner", "Z Banner Title")]
    assert localization_title(only_titles) == "Mod Name"  # same priority: shorter wins
    assert localization_title([("a_mod_name", "Bb"), ("b_mod_name", "Ab")]) == "Ab"  # then text
    assert localization_title([("quirk_name_foo", "Quirk"), ("x_name", "Zz")]) == "Zz"
    assert localization_title([]) is None
    assert localization_title([("other_id", "Text"), ("tooltip_x", "Tooltip")]) is None
    assert localization_title([("hero_class_name_x", "x" * 81)]) is None
    assert localization_title([("hero_class_name_x", "50% off")]) is None
    assert localization_title([("hero_class_name_x", "")]) is None


def test_localization_title_accepts_any_sequence_of_pairs() -> None:
    assert localization_title((("hero_class_name_x", "Hero"),)) == "Hero"


def test_localization_title_normalizes_raw_entries_exactly_once() -> None:
    """dd2.py:3565-3567: id lower-cased; text stripped, unescaped ONCE, whitespace collapsed."""
    assert localization_title(mf.LOC_ENTITIES) == "A &amp; B"
    assert localization_title([("HERO_CLASS_NAME_X", " Two\n  Words ")]) == "Two Words"
    assert localization_title([("hero_class_name_x", "&nbsp;x")]) == " x"  # no second strip
    assert localization_title([("hero_class_name_x", "x" * 79 + "\n\n x")]) is None  # 81 chars


def test_internal_code_title_contract() -> None:
    assert internal_code_title((("heroes", ("sakura", "zz_other")),)) == "Sakura"
    assert internal_code_title((("monsters", ("the-big_one", "zz_beast")),)) == "THE BIG ONE"
    assert internal_code_title((("monsters", ("zz_beast",)),)) == "ZZ Beast"
    assert internal_code_title((("heroes", ("vestal_rework",)),)) == "Vestal Rework"
    assert internal_code_title((("raid", ("camping",)),)) == "Camping"
    assert internal_code_title((("dungeons", ("ruins_x",)),)) == "Ruins X"
    assert internal_code_title(()) is None
    assert (
        internal_code_title((("trinkets", ("x",)), ("quirks", ("y",)))) is None
    )  # not a code root
    assert internal_code_title((("heroes", ()),)) is None
    assert internal_code_title((("heroes", ("桜",)),)) is None  # no Latin -> skipped


def test_internal_code_title_prefers_heroes_then_monsters_then_dungeons() -> None:
    subdirs = (("heroes", ("vestal_rework",)), ("monsters", ("aaa",)))
    assert internal_code_title(subdirs) == "Vestal Rework"
    assert internal_code_title((("monsters", ("aaa",)), ("dungeons", ("bbb",)))) == "AAA"


def test_internal_code_title_capitalization_rules() -> None:
    assert (
        internal_code_title((("heroes", ("mcDonald_x",)),)) == "McDonald X"
    )  # first char upper only
    assert internal_code_title((("heroes", ("UPPER_case",)),)) == "UPPER Case"
    assert internal_code_title((("heroes", ("a_b_c",)),)) == "A B C"
    assert internal_code_title((("heroes", ("abcd",)),)) == "Abcd"


# ----------------------------------------------------------------- save identity


def _project(**kwargs: Any) -> ProjectInfo:
    info = parse_project(mf.project_xml(**kwargs).encode("utf-8"))
    assert info is not None
    return info


@pytest.mark.parametrize(
    ("folder", "workshop", "wid", "project", "expected"),
    [
        (
            "0001_my_mod",
            False,
            "",
            _project(title="My Great Mod"),
            ("My Great Mod", "mod_local_source"),
        ),
        ("123", True, "123", _project(title="T", published_id="456"), ("456", "Steam")),
        ("123", True, "123", None, ("123", "Steam")),
        ("123", True, "123", _project(title="T"), ("123", "Steam")),
        ("0001_my_mod", False, "", None, ("my_mod", "mod_local_source")),
        (
            "0005_gold_mod",
            False,
            "",
            _project(title="50% more gold"),
            ("gold_mod", "mod_local_source"),
        ),
        ("sakura_skin", False, "", _project(title="桜"), ("sakura_skin", "mod_local_source")),
        ("2900000001", True, "2900000001", _project(title="桜"), ("2900000001", "Steam")),
        (
            "cool_mod",
            False,
            "",
            _project(title="Cool", published_id="333"),
            ("Cool", "mod_local_source"),
        ),
        ("weird_name", True, "", _project(title="Weird"), ("Weird", "mod_local_source")),
        ("weird_name", True, "", None, ("weird_name", "mod_local_source")),
        ("1234567_old", True, "1234567", _project(title="Old"), ("1234567", "Steam")),
    ],
)
def test_resolve_save_identity_contract(
    folder: str, workshop: bool, wid: str, project: ProjectInfo | None, expected: tuple[str, str]
) -> None:
    identity = resolve_save_identity(
        folder_key=folder, under_workshop=workshop, path_workshop_id=wid, project=project
    )
    assert identity == SaveIdentity(*expected)


# ----------------------------------------------------------------- derive_mod_info


def _snapshot(**overrides: Any) -> ModSnapshot:
    base = ModSnapshot(
        key=ModId("0001_my_mod"),
        source_id="local_folder",
        kind=factories.SourceKind.LOCAL,
        path=factories.LOCAL_ROOT / "0001_my_mod",
        root=factories.LOCAL_ROOT,
        under_workshop=False,
        path_workshop_id="",
        project=_project(title="My Great Mod", major="1", minor="2", tags=("Class",)),
        localization_entries=(),
        top_level_dirs=frozenset({"heroes"}),
        code_subdirs=(("heroes", ("mymod",)),),
        files=frozenset({"heroes/mymod/mymod.info.darkest"}),
        newest_mtime=None,
        project_mtime=None,
        localization_signature="",
        acf_timeupdated="",
        preview_path=None,
        preview_mtime_ns=None,
    )
    return dataclasses.replace(base, **overrides) if overrides else base


def _workshop_snapshot(folder: str, project: ProjectInfo | None, **overrides: Any) -> ModSnapshot:
    return _snapshot(
        key=ModId(folder),
        source_id="steam_workshop",
        kind=factories.SourceKind.WORKSHOP,
        path=factories.WORKSHOP_ROOT / folder,
        root=factories.WORKSHOP_ROOT,
        under_workshop=True,
        path_workshop_id=mf.path_workshop_id(folder, under_workshop=True),
        project=project,
        **overrides,
    )


def test_derive_mod_info_copies_facts_and_derives_names() -> None:
    snap = _snapshot(newest_mtime=float(mf.MID_JULY), project_mtime=float(mf.MID_MARCH))
    info = derive_mod_info(snap, tz=UTC)
    assert isinstance(info, ModInfo)
    assert info.id == snap.key and info.kind is snap.kind and info.path == snap.path
    assert info.root == snap.root and info.source_id == snap.source_id
    assert info.title == "My Great Mod"
    assert info.project_title == "My Great Mod"
    assert info.save_identity == SaveIdentity("My Great Mod", SaveSource.LOCAL)
    assert info.workshop_id == ""
    assert info.version_label == "1.2"
    assert info.updated_label == "07/24"
    assert info.black_reliquary is False
    assert info.tags == ("Class",)
    assert info.top_level_dirs == snap.top_level_dirs
    assert info.code_subdirs == snap.code_subdirs
    assert info.files == snap.files
    assert info.load_after_hints == ()
    assert info.shadowed == ()
    assert info.signature.project_mtime == snap.project_mtime
    assert info.signature.localization_signature == snap.localization_signature
    assert info.signature.workshop_timeupdated == snap.acf_timeupdated


def test_derive_mod_info_without_project_xml() -> None:
    info = derive_mod_info(_snapshot(project=None), tz=UTC)
    assert info.project_title is None
    assert info.title == "my_mod"
    assert info.save_identity == SaveIdentity("my_mod", SaveSource.LOCAL)
    assert info.version_label == "" and info.updated_label == ""
    assert info.tags == ()


def test_updated_label_prefers_acf_then_newest_then_project() -> None:
    both = {"newest_mtime": float(mf.MID_JULY), "project_mtime": float(mf.MID_MARCH)}
    assert (
        derive_mod_info(_snapshot(acf_timeupdated="1731672000", **both), tz=UTC).updated_label
        == "11/24"
    )
    assert derive_mod_info(_snapshot(**both), tz=UTC).updated_label == "07/24"
    assert (
        derive_mod_info(_snapshot(project_mtime=float(mf.MID_MAY)), tz=UTC).updated_label == "05/24"
    )
    assert derive_mod_info(_snapshot(), tz=UTC).updated_label == ""
    assert (
        derive_mod_info(_snapshot(acf_timeupdated="garbage", **both), tz=UTC).updated_label
        == "07/24"
    )


def test_updated_label_uses_the_given_timezone() -> None:
    late = datetime(2024, 3, 31, 23, 30, tzinfo=UTC).timestamp()
    assert derive_mod_info(_snapshot(newest_mtime=late), tz=UTC).updated_label == "03/24"
    plus_two = timezone(timedelta(hours=2))
    assert derive_mod_info(_snapshot(newest_mtime=late), tz=plus_two).updated_label == "04/24"
    assert (
        derive_mod_info(_snapshot(acf_timeupdated=str(int(late))), tz=plus_two).updated_label
        == "04/24"
    )


def test_workshop_id_comes_from_the_project_only_under_the_workshop() -> None:
    renamed = _workshop_snapshot("1111111111", _project(title="Renamed", published_id="2222222222"))
    info = derive_mod_info(renamed, tz=UTC)
    assert info.workshop_id == "2222222222"
    assert info.save_identity == SaveIdentity("2222222222", SaveSource.STEAM)
    bare = derive_mod_info(_workshop_snapshot("4444444444", None), tz=UTC)
    assert bare.workshop_id == "4444444444"
    assert bare.save_identity == SaveIdentity("4444444444", SaveSource.STEAM)
    local = derive_mod_info(_snapshot(project=_project(title="Cool", published_id="333")), tz=UTC)
    assert local.workshop_id == ""
    assert local.save_identity == SaveIdentity("Cool", SaveSource.LOCAL)
    weird = derive_mod_info(_workshop_snapshot("weird_name", _project(title="Weird")), tz=UTC)
    assert weird.workshop_id == ""
    assert weird.save_identity == SaveIdentity("Weird", SaveSource.LOCAL)


def test_title_chain_latin_gate_and_fallbacks() -> None:
    cjk = _project(title="桜のスキン")
    assert (
        derive_mod_info(_snapshot(key=ModId("sakura_skin"), project=cjk), tz=UTC).title
        == "sakura_skin"
    )
    numeric = _workshop_snapshot("2900000001", cjk, code_subdirs=(("heroes", ("sakura",)),))
    assert derive_mod_info(numeric, tz=UTC).title == "Sakura"
    loc = _workshop_snapshot("2900000001", cjk, localization_entries=mf.LOC_RANKING)
    assert derive_mod_info(loc, tz=UTC).title == "Abomination Rework"
    bad = _snapshot(
        key=ModId("9999_loc_mod"),
        project=_project(title="50% off"),
        localization_entries=mf.LOC_RANKING,
    )
    assert derive_mod_info(bad, tz=UTC).title == "Abomination Rework"
    code_only = _snapshot(
        key=ModId("0002_bare"), project=None, code_subdirs=(("heroes", ("bare",)),)
    )
    assert derive_mod_info(code_only, tz=UTC).title == "bare"  # folder not numeric: no code title
    numeric_no_project = _workshop_snapshot(
        "4444444444", None, code_subdirs=(("heroes", ("vestal_rework",)),)
    )
    assert derive_mod_info(numeric_no_project, tz=UTC).title == "Vestal Rework"


def test_black_reliquary_and_hints_come_from_the_project() -> None:
    project = _project(
        title="BR Weapons",
        tags=("Black_Reliquary", "Trinkets"),
        description="Load this after:\n- Black Reliquary\n- Other\n",
    )
    info = derive_mod_info(_snapshot(project=project), tz=UTC)
    assert info.black_reliquary is True
    assert info.load_after_hints == ("Black Reliquary", "Other")
    assert info.tags == ("Black_Reliquary Trinkets", "Black_Reliquary", "Trinkets")


# ----------------------------------------------------------------- display helpers (contract)


def test_display_name_rules() -> None:
    chorus = factories.workshop_mod("2248772895", title="The Chorus")
    assert display_name(chorus, None) == "The Chorus [2248772895]"
    assert display_name(chorus, "") == "The Chorus [2248772895]"
    old = factories.workshop_mod("1234567_old_style", title="Old Style", workshop_id="1234567")
    assert display_name(old, None) == "Old Style"
    renamed = factories.workshop_mod("1111111111", title="T", workshop_id="2222222222")
    assert display_name(renamed, None) == "T [1111111111]"
    other_id = factories.workshop_mod("named_upload", title="T", workshop_id="2222222222")
    assert display_name(other_id, None) == "T [2222222222]"
    local = factories.local_mod("0001_my_mod", title="My Great Mod")
    assert display_name(local, None) == "My Great Mod"
    fallback = factories.local_mod("0001_my_mod")  # title == stripped folder
    assert display_name(fallback, None) == "my_mod"
    same = factories.local_mod("sakura_skin", title="sakura_skin")
    assert display_name(same, None) == "sakura_skin"
    prefixed_same = factories.local_mod("0001_x", title="0001_x")
    assert display_name(prefixed_same, None) == "x"
    entity = factories.local_mod("rk", title="Rogue &amp; Knight")
    assert display_name(entity, None) == "Rogue & Knight"


def test_display_name_nickname_and_black_reliquary_prefix() -> None:
    info = factories.local_mod("br_patch", title="BR Weapons", black_reliquary=True)
    assert display_name(info, None) == "[BR] BR Weapons"
    assert display_name(info, "  Nick  ") == "[BR] Nick"
    assert display_name(info, "[BR] Already") == "[BR] Already"
    assert display_name(info, "A &amp; B") == "[BR] A & B"
    plain = factories.local_mod("plain", title="Plain")
    assert display_name(plain, "Nick") == "Nick"


def test_display_suffix_and_name_with_suffix() -> None:
    chorus = factories.workshop_mod(
        "2248772895", title="The Chorus", version_label="1.2", updated_label="03/24"
    )
    assert display_suffix(chorus) == "1.2"
    assert display_name_with_suffix(chorus, None) == "The Chorus [2248772895] (1.2)"
    dated = factories.local_mod("x", title="X", updated_label="03/24")
    assert display_suffix(dated) == "03/24"
    assert display_name_with_suffix(dated, "Nick") == "Nick (03/24)"
    bare = factories.local_mod("x", title="X")
    assert display_suffix(bare) == ""
    assert display_name_with_suffix(bare, None) == "X"


def test_sort_key_rules() -> None:
    chorus = factories.workshop_mod("2248772895", title="The Chorus")
    assert sort_key(chorus, None) == "chorus"
    assert sort_key(chorus, "The Nick") == "nick"
    assert sort_key(chorus, "Zed &amp; Co") == "zed & co"
    assert sort_key(factories.local_mod("the_x", title="the_x"), None) == "the_x"
    assert sort_key(factories.local_mod("0001_Theme", title="0001_Theme"), None) == "theme"
    assert (
        sort_key(factories.local_mod("x", title="  The  Alpha "), None) == " alpha"
    )  # strip then cut "the "


def test_duplicate_keys_contract() -> None:
    chorus = factories.workshop_mod("2248772895", title="The Chorus")
    assert duplicate_keys(chorus) == ("id:2248772895", "name:the chorus")
    local = factories.local_mod("0001_my_mod", title="My Great Mod")
    assert duplicate_keys(local) == ("name:my great mod", "name:my mod", "name:0001 my mod")
    short = factories.local_mod("zed", title="Zed")
    assert duplicate_keys(short) == ()
    copy = factories.local_mod("0007_the_chorus", title="The Chorus")
    assert set(duplicate_keys(copy)) & set(duplicate_keys(chorus)) == {"name:the chorus"}


def test_category_memory_keys_contract() -> None:
    chorus = factories.workshop_mod("2248772895", title="The Chorus")
    assert category_memory_keys(chorus) == (
        "2248772895",
        "norm:2248772895",
        "The Chorus",
        "norm:the chorus",
    )
    local = factories.local_mod("0001_my_mod", title="My Great Mod")
    assert category_memory_keys(local) == (
        "My Great Mod",
        "norm:my great mod",
        "my_mod",
        "norm:my mod",
        "0001_my_mod",
        "norm:0001 my mod",
    )
    no_project = factories.local_mod("0001_my_mod", project_title=None)
    assert category_memory_keys(no_project) == (
        "my_mod",
        "norm:my mod",
        "0001_my_mod",
        "norm:0001 my mod",
    )


# ----------------------------------------------------------------- goldens (no oracle needed)


def test_goldens_are_pinned_to_the_legacy_commit() -> None:
    assert HELPERS["legacy_commit"] == "31e85d6"
    assert CASES["legacy_commit"] == "31e85d6"
    assert {c["id"] for c in CASES["cases"]} == {spec.id for spec in mf.CASES}


def test_golden_normalize_mod_identity() -> None:
    table = HELPERS["normalize_mod_identity"]
    corpus = mf.identity_corpus(table["seed"], table["count"])
    pairs = table["pairs"]
    assert [p[0] for p in pairs] == corpus, "corpus generator drifted: regenerate the goldens"
    for raw, expected in pairs:
        assert normalize_mod_identity(raw) == expected, raw


def test_golden_title_predicates() -> None:
    rows = HELPERS["titles"]
    assert [r["text"] for r in rows] == list(mf.TITLE_CORPUS)
    for row in rows:
        text = row["text"]
        assert text_has_latin(text) is row["has_latin"], text
        assert looks_like_numeric_id(text) is row["numeric"], text
        assert is_bad_display_title(text) is row["bad"], text


def test_golden_small_helpers() -> None:
    from src.core.project_xml import is_black_reliquary_tagged, version_label

    for major, minor, expected in HELPERS["version_label"]:
        assert version_label(major, minor) == expected, (major, minor)
    for row in HELPERS["black_reliquary"]:
        assert is_black_reliquary_tagged(tuple(row["tags"])) is row["tagged"], row
    for folder, expected in HELPERS["save_name"]:
        assert strip_numeric_prefix(folder) == expected, folder


def core_record(info: ModInfo) -> dict[str, object]:
    """The identity facts in the shape ``mod_facts.legacy_record`` produces."""
    return {
        "title": info.title,
        "published_file_id": info.workshop_id,
        "save_identity": list(info.save_identity.as_tuple()),
        "version_label": info.version_label,
        "updated_label": info.updated_label,
        "black_reliquary": info.black_reliquary,
        "project_mtime": info.signature.project_mtime,
        "localization_signature": info.signature.localization_signature,
        "workshop_timeupdated": info.signature.workshop_timeupdated,
        "legacy_tags": list(info.tags),
        "display_name": display_name(info, None),
        "display_suffix": display_suffix(info),
        "display_name_with_suffix": display_name_with_suffix(info, None),
        "sort_name": sort_key(info, None),
        "duplicate_keys": list(duplicate_keys(info)),
        "category_memory_keys": list(category_memory_keys(info)),
    }


def core_nickname_record(info: ModInfo, nickname: str) -> dict[str, object]:
    return {
        "display_name": display_name(info, nickname),
        "display_name_with_suffix": display_name_with_suffix(info, nickname),
        "sort_name": sort_key(info, nickname),
    }


@pytest.fixture(scope="module")
def case_dirs(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Path]:
    return mf.materialize_all(tmp_path_factory.mktemp("identity"))


@pytest.mark.parametrize("case", CASES["cases"], ids=[str(c["id"]) for c in CASES["cases"]])
def test_identity_matches_golden(case: dict[str, Any], case_dirs: dict[str, Path]) -> None:
    spec = mf.spec_by_id(case["id"])
    assert spec.digest() == case["spec_digest"], "case spec drifted: regenerate the goldens"
    snapshot = mf.snapshot_from_dir(case_dirs[spec.id], acf=dict(spec.acf))
    info = derive_mod_info(snapshot, tz=LOCAL_TZ)
    assert core_record(info) == case["record"]
    for nickname, expected in case["nicknames"].items():
        assert core_nickname_record(info, nickname) == expected, nickname


def test_local_published_id_feeds_the_category_memory(case_dirs: dict[str, Path]) -> None:
    """dd2.py:4063-4081 project_identity_name returns the raw <PublishedFileId> even outside the
    workshop, so a LOCAL mod's category memory also carries that id (workshop_id stays "")."""
    spec = mf.spec_by_id("pid_outside_workshop")
    golden = next(c for c in CASES["cases"] if c["id"] == spec.id)
    assert "3333333333" in golden["record"]["category_memory_keys"]
    snapshot = mf.snapshot_from_dir(case_dirs[spec.id])
    info = derive_mod_info(snapshot, tz=LOCAL_TZ)
    assert info.workshop_id == ""
    keys = category_memory_keys(info)
    assert keys == ("Cool Mod", "norm:cool mod", "3333333333", "norm:3333333333", "cool_mod")


# ----------------------------------------------------------------- live parity vs the pinned oracle


@pytest.mark.legacy
def test_normalize_mod_identity_matches_legacy_on_2k_strings(legacy: LegacyOracle) -> None:
    dd2 = legacy.module("dd2")
    for text in mf.identity_corpus(2024, 2000):
        assert normalize_mod_identity(text) == dd2.normalize_mod_identity(text), repr(text)
    assert normalize_mod_identity("") == dd2.normalize_mod_identity(None)


@pytest.mark.legacy
def test_title_predicates_match_legacy(legacy: LegacyOracle) -> None:
    dd2 = legacy.module("dd2")
    rng = random.Random(99)
    extra = [
        "".join(rng.choice(mf._IDENTITY_POOL) for _ in range(rng.randint(0, 8))) for _ in range(500)
    ]
    for text in (*mf.TITLE_CORPUS, *extra):
        assert text_has_latin(text) is dd2.text_has_latin(text), repr(text)
        assert looks_like_numeric_id(text) is dd2.looks_like_numeric_id(text), repr(text)
        assert is_bad_display_title(text) is dd2.is_bad_display_title(text), repr(text)
    for folder in (*mf.SAVE_NAME_CASES, *extra):
        assert strip_numeric_prefix(folder) == dd2.ModManager.save_name(None, folder), repr(folder)


@pytest.mark.legacy
@pytest.mark.parametrize("spec", mf.CASES, ids=[s.id for s in mf.CASES])
def test_identity_matches_legacy_read_mod_metadata(
    legacy: LegacyOracle, spec: mf.ModDirSpec, case_dirs: dict[str, Path]
) -> None:
    dd2 = legacy.module("dd2")
    categories = legacy.module("categories")
    folder = case_dirs[spec.id]
    manager = mf.legacy_manager(dd2, {spec.folder: folder}, acf=dict(spec.acf))
    expected = mf.legacy_record(manager, categories, dd2, spec.folder)
    snapshot = mf.snapshot_from_dir(folder, acf=dict(spec.acf))
    info = derive_mod_info(snapshot, tz=LOCAL_TZ)
    assert core_record(info) == expected
    for nickname in spec.nicknames:
        assert core_nickname_record(info, nickname) == mf.legacy_nickname_record(
            manager, spec.folder, nickname
        )


@pytest.mark.legacy
def test_localization_title_matches_legacy_on_shuffled_tables(
    legacy: LegacyOracle, tmp_path: Path
) -> None:
    dd2 = legacy.module("dd2")
    rng = random.Random(21)
    pool = [
        *mf.LOC_RANKING,
        *mf.LOC_ENTITIES,
        ("hero_class_name_b", "Bb"),
        ("hero_class_name_a", "Ab"),
        ("x_class_name_y", "Same"),
        ("y_class_name_x", "Same"),
        ("str_title_x", "A title"),
        ("foo_name_", "Trail"),
        ("name_x", "No match"),
        ("abc", "桜"),
    ]
    for index in range(40):
        entries = rng.sample(pool, rng.randint(0, len(pool)))
        folder = tmp_path / f"m{index}"
        (folder / "localization").mkdir(parents=True)
        (folder / "localization" / "t.string_table.xml").write_text(
            mf.string_table(entries), "utf-8"
        )
        manager = mf.legacy_manager(dd2, {folder.name: folder})
        expected = manager.localization_title_for_mod(folder.name)
        got = localization_title(mf._localization_entries(folder))
        assert (got or "") == expected, entries


@pytest.mark.legacy
def test_internal_code_title_matches_legacy(legacy: LegacyOracle, tmp_path: Path) -> None:
    dd2 = legacy.module("dd2")
    layouts = {
        "a": ("heroes/sakura", "heroes/zz_other", "monsters/aaa"),
        "b": ("monsters/the-big_one", "monsters/zz_beast", "dungeons/ruins_x"),
        "c": ("raid/camping",),
        "d": ("trinkets/x", "quirks/y"),
        "e": ("heroes/桜", "monsters/beast"),
        "f": ("heroes/mcDonald_x", "heroes/UPPER_case"),
        "g": (),
        "h": ("heroes/a_b_c",),
        "i": ("heroes/__",),
    }
    for name, dirs in layouts.items():
        folder = tmp_path / name
        folder.mkdir()
        for rel in dirs:
            (folder / rel).mkdir(parents=True)
        manager = mf.legacy_manager(dd2, {name: folder})
        expected = manager.internal_code_title_for_mod(name)
        got = internal_code_title(mf._code_subdirs(folder))
        assert (got or "") == expected, name
